### ISSUE TITLE
sample of training dataset?

### ISSUE THREAD

**Issue by EmbraceLife** [jperl/stock2vec#1]
Hi @jperl 

Thanks a lot for sharing this repo!

I would like to reproduce your work. If you can't share the training dataset, could you upload a smaller sample of the training dataset you use? This way I can check what kind of stock info is used in detail, so that I can find equivalent datasets to reproduce your work.

Best

**Comment by jperl** [comment]
Hi @EmbraceLife the way I built the data set was by combining the prices from [here](https://www.quandl.com/data/WIKI-Wiki-EOD-Stock-Prices) with the fundamentals from [here](https://www.quandl.com/data/SF1-Core-US-Fundamentals-Data) and you can follow [these instructions](https://github.com/jperl/stock2vec/blob/master/Preprocess%20Stock%20Data.ipynb) to generate the training data.

Unfortunately the fundamentals is a paid dataset which I do not have the license to share so I cannot upload a sample of the training dataset.

**Comment by EmbraceLife** [comment]
how about just headers of the fundamentals, without values? thanks
