### ISSUE TITLE
'prices.csv' missing

### ISSUE THREAD

**Issue by gmihaila** [jperl/stock2vec#3]
Could you please provide a link to **prices.csv** ? Or added on your repo. if the memory allows you?

Thank you! This is great work!

**Comment by jperl** [comment]
Hi unfortunately I reinstalled my computer and no longer have it. I download it from here https://www.quandl.com/databases/WIKIP/documentation

**Comment by gmihaila** [comment]
Thank you for your reply @jperl 
I did get that dataset, but I'm missing the fundamentals data from Sharadar that you mentioned in your article. Is that something you are willing to share? 😃

**Comment by jperl** [comment]
Unfortunately I reinstalled my computer since then and no longer have it :(.
